### PR TITLE
mapbox gl map

### PR DESCRIPTION
**Pull request by sbma44**
@miklb per our conversation, here's a minimal GL map. I've created a style that incorporates evacuation route geometry and otherwise attempted to stick pretty close to what's on the site now. If you feel this is on the right track, I should:

- [x] move token to site config
- [x] modularize map, move CSS to sitewide SCSS, implement on homepage
- [x] add geolocation feature
- [x] label evacuation routes somehow

image

### CODE REVIEW

**Comment by tdooner** [comment]
Hey @sbma44 this looks great, thank you so much for making this happen! I'll leave it up to @miklb to do the QA and to get this merged.

We're going to keep the <iframe> to florenceshelters.com on the homepage for now, since it has the geolocation ability. Once we get that on this map we can switch it out on the homepage.

This is awesome. 👏

**Comment by sbma44** [comment]
ok, made the above changes. please have a look. would appreciate your dropping in a CfA-owned map token rather than the one in there now, which will be going away after this dev process completes. I'm told the CfA account should be all set for couponing already, but if that's wrong don't hesitate to let me know so I can sort it out.

**Comment by sbma44** [comment]
image

**Comment by sbma44** [comment]
per slack I see this was reverted due to features missing from the iframe map. I'll add those now:

- [x] telephone links -- this is in place via `tel:` hyperlink already
- [x] notes -- I can add this, no problem
- [x] disabling "accepting people" -- seems wise, but lmk if there are other items that should be struck. "needs" wasn't populated anywhere when I looked at the data
- [x] directions -- easy enough to link out to google though of course it :broken_heart:  me. I'll have a quick look at alternatives but won't let this slow work.

I'll add:
- [ ] ~~remove unused data-uri from stylesheet~~ I dreamed this
- [x] robustify className toggling in JS

**Comment by sbma44** [comment]
moving to https://github.com/hurricane-response/florence_website/pull/27

**Pull request merged**
